### ISSUE TITLE
Kodi 19+

### ISSUE THREAD

**Issue by probonopd** [kasi45/plugin.video.mediathekviewweb#2]
Do you think we can get this to work on Kodi 19 and later?

**Comment by kasi45** [comment]
Das Plugin funzt unter Kodi19

**Comment by probonopd** [comment]
Ich meinte Kodi 20.

In allen Dateien muss `xbmc.translatePath` durch `xbmcvfs.translatePath` ersetzt werden und in den betroffenen Dateien muss, soweit nicht bereits vorhanden, `import xbmcvfs` hinzugefügt werden. Dann läuft es auf Kodi 20, das habe ich getestet. Ob es dann auf Kodi 18 und 19 auch noch läuft habe ich allerdings noch nicht testen können.

Soll ich einen Pull Request schicken?

**Comment by kasi45** [comment]
done

**Comment by probonopd** [comment]
Vielen Dank!
Klasse Plugin :+1:
